add update_ghost_values in normal_flux_calculation
exadg/exadg pull request #341
Opened 2023-02-16 13:20 UTC by gilrrei

Add missing `update_ghost_values` in normal_flux_calculation

2023-02-16 15:13 UTC, nfehn commented
looks good from my side

2023-02-16 15:13 UTC, nfehn approved these changes

2023-02-16 22:03 UTC, peterrum requested changes

2023-02-17 08:23 UTC, nfehn commented on include/exadg/postprocessor/normal_flux_calculation.cpp
> +  solution.update_ghost_values();
Just a minor comment: Let's write `if(not(has_ghost_elements))`. (We should make efforts to only use `and`/`or` in ExaDG for better readability.)

Furthermore, the convention in ExaDG is to write `bool const`. ("const is a trailing keyword.")

2023-02-17 08:41 UTC, nfehn approved these changes

2023-02-17 09:18 UTC, peterrum approved these changes
Thx!

2023-03-06 12:52 UTC, merged